// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiip2lQz0Uvj3FjSmdCKUF1qQ0YEHa9Kg',
    appId: '1:973328939824:web:f743cfc9eb87d3f63e26f5',
    messagingSenderId: '973328939824',
    projectId: 'ai-dpmms',
    authDomain: 'ai-dpmms.firebaseapp.com',
    storageBucket: 'ai-dpmms.firebasestorage.app',
    measurementId: 'G-N0QN85E7BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdVntpVta1WKt8tIb5LEBstCO3e0FJYU',
    appId: '1:973328939824:android:314b045af2d5ea993e26f5',
    messagingSenderId: '973328939824',
    projectId: 'ai-dpmms',
    storageBucket: 'ai-dpmms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHeDogfpB6zOnn3VX7Pl8-Wkx7tRdFV4c',
    appId: '1:973328939824:ios:a5776b3c466892073e26f5',
    messagingSenderId: '973328939824',
    projectId: 'ai-dpmms',
    storageBucket: 'ai-dpmms.firebasestorage.app',
    iosBundleId: 'com.example.aiDpmmsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHeDogfpB6zOnn3VX7Pl8-Wkx7tRdFV4c',
    appId: '1:973328939824:ios:a5776b3c466892073e26f5',
    messagingSenderId: '973328939824',
    projectId: 'ai-dpmms',
    storageBucket: 'ai-dpmms.firebasestorage.app',
    iosBundleId: 'com.example.aiDpmmsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiip2lQz0Uvj3FjSmdCKUF1qQ0YEHa9Kg',
    appId: '1:973328939824:web:940c533190b438443e26f5',
    messagingSenderId: '973328939824',
    projectId: 'ai-dpmms',
    authDomain: 'ai-dpmms.firebaseapp.com',
    storageBucket: 'ai-dpmms.firebasestorage.app',
    measurementId: 'G-RWNEDVD54M',
  );
}
